[[redirects]]
from = "/admin/*"
to = "/admin/index.html"
status = 200

[[headers]]
for = "/admin/*"
[headers.values]
X-Frame-Options = "DENY"
X-XSS-Protection = "1; mode=block"
X-Content-Type-Options = "nosniff"
Content-Security-Policy = "default-src 'self' https:; script-src 'self' https://identity.netlify.com https://unpkg.com; style-src 'self' https: 'unsafe-inline'; img-src 'self' https: data:; font-src 'self' https: data:;"