backend:
  name: git-gateway
  branch: main # Branch to update (master in older repos)

media_folder: "assets/image" # Media files will be stored here
public_folder: "/assets/image" # Public path for media files

collections:
  - name: "blog"
    label: "Blog Posts"
    folder: "content/blog"
    create: true
    slug: "{{year}}-{{month}}-{{day}}-{{slug}}"
    fields:
      - {label: "Layout", name: "layout", widget: "hidden", default: "blog"}
      - {label: "Title", name: "title", widget: "string"}
      - {label: "Featured Image", name: "featured_image", widget: "image"}
      - {label: "Excerpt", name: "excerpt", widget: "text"}
      - {label: "Content", name: "content", widget: "markdown"}
      - {label: "Date", name: "date", widget: "datetime"}
      - {label: "Featured Post", name: "featured", widget: "boolean", default: false}
      - {label: "Category", name: "category", widget: "select", options: ["News", "Articles", "Updates"]}