backend:
  name: git-gateway
  branch: main  # Your Git branch

media_folder: "static/uploads"  # Stores uploaded images
public_folder: "/uploads"

collections:
  # About Page Content
  - name: "about"
    label: "About Page"
    files:
      # Hero Section
      - file: "content/about/hero.md"
        label: "Hero Section"
        fields:
          - { name: "title", label: "Hero Title", widget: "string" }
          - { name: "description", label: "Hero Description", widget: "text" }
          - { name: "background_image", label: "Hero Background Image", widget: "image" }

      # Mission/Vision/Commitment Blocks
      - file: "content/about/content.md"
        label: "Content Blocks"
        fields:
          - { name: "mission_title", label: "Mission Title", widget: "string" }
          - { name: "mission_text", label: "Mission Text", widget: "markdown" }
          - { name: "vision_title", label: "Vision Title", widget: "string" }
          - { name: "vision_text", label: "Vision Text", widget: "markdown" }
          - { name: "commitment_title", label: "Commitment Title", widget: "string" }
          - { name: "commitment_text", label: "Commitment Text", widget: "markdown" }

      # Team Members (Repeatable)
      - file: "content/about/team.md"
        label: "Team Members"
        fields:
          - { name: "team_members", label: "Team", widget: "list", fields: [
            { name: "name", label: "Name", widget: "string" },
            { name: "role", label: "Role", widget: "string" },
            { name: "bio", label: "Bio", widget: "text" },
            { name: "image", label: "Photo", widget: "image" },
            { name: "linkedin", label: "LinkedIn URL", widget: "string" }
          ] }